#!/bin/bash

wget -O GCM.deb "https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.632/gcmcore-linux_amd64.2.0.632.34631.deb" &&
sudo dpkg -i GCM.deb &&
git-credential-manager-core configure
